# Utilise une image de base officielle PHP avec Apache
FROM php:8.2-apache

# Configure explicit custom 404 page at Apache level.
RUN printf "ErrorDocument 404 /404.php\n" > /etc/apache2/conf-available/custom-errors.conf \
	&& a2enconf custom-errors

# Copie les fichiers de votre projet (dossiers 'html' et 'Php')
# vers le dossier web du serveur dans le conteneur
COPY html/ /var/www/html/
COPY Php/ /var/www/html/Php/

# (Optionnel) Il y a peut-être d'autres commandes ici,
# comme l'installation d'extensions PHP (par exemple pour MySQL)
RUN docker-php-ext-install pdo pdo_mysql mysqli

# L'image de base 'php:8.2-apache' expose
# automatiquement le port 80.
# La ligne EXPOSE 80 peut être là ou être implicite.
EXPOSE 5001